# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: DNS4ACME
# Binary builds:
builds:
  - id: "binary"
    main: ./cmd/dns4acme
    binary: dns4acme
    env:
      - CGO_ENABLED=0
    tags:
      - kubernetes
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
# Packaging
archives:
  - id: default
    files:
    - LICENSE.md
dockers:
  - use: buildx
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - LICENSE.md
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:latest-amd64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Version }}-amd64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}-amd64
  - use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - LICENSE.md
    build_flag_templates:
      - "--platform=linux/arm64"
    image_templates:
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:latest-arm64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Version }}-arm64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}.{{ .Minor }}-arm64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}-arm64
docker_manifests:
  - name_template: ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:latest
    image_templates:
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:latest-amd64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:latest-arm64
  - name_template: ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Version }}
    image_templates:
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Version }}-amd64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Version }}-arm64
  - name_template: ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}.{{ .Minor }}-arm64
  - name_template: ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}
    image_templates:
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}-amd64
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}:{{ .Major }}-arm64
# Software Bill of Materials, signatures, etc:
sboms:
  - id: default
    cmd: go
    args:
      - "run"
      - "github.com/dns4acme/dns4acme/tools/generate-archive-sbom"
      - "${artifact}"
      - "${document}"
signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all
docker_signs:
  - artifacts: manifests
    cmd: go
    args:
      - "run"
      - "github.com/dns4acme/dns4acme/tools/image-sbom-and-signature"
      - ghcr.io/{{- envOrDefault "GITHUB_REPOSITORY" "dns4acme/dsn4acme" | tolower -}}@${digest}
      # Note: this MUST be upper case as the Cosign subject is upper case. The following line must match the subject EXACTLY.
      - https://github.com/{{- envOrDefault "GITHUB_REPOSITORY" "DNS4ACME/DNS4ACME" -}}/.github/workflows/main.yml@refs/tags/v{{ .Version }}
