rules:
  - pattern: "BSD-*"
    name: "bsd-allow"
    mode: "allow"
    reason: "Compatible license"
  - pattern: "MIT"
    name: "mit-allow"
    mode: "allow"
    reason: "Compatible license"
  - pattern: "Unlicense"
    name: "unlicense-allow"
    mode: "allow"
    reason: "Compatible license"
  - pattern: "CC0"
    name: "cc0-allow"
    mode: "allow"
    reason: "Compatible license"
  - pattern: "Apache-2.0"
    name: "apache-2-allow"
    mode: "allow"
    reason: "Compatible license"
  - pattern: "ISC"
    name: "isc-allow"
    mode: "allow"
    reason: "Compatible license"
  - pattern: "*"
    name: "default-deny-all"
    mode: "deny"
    reason: "Incompatible or unknown license"
