apiVersion: dns4acme.github.io/v1
kind: Domain
metadata:
  name: example.com
  namespace: dns4acme
spec:
  # Set a strong update key in base64-encoding here:
  update_key: EeheighupumieZ0saya0aedaiV7quaj9
